const SUBMIT_IMAGE_BEGIN = 'SUBMIT_IMAGE_BEGIN';
const SUBMIT_IMAGE_SUCCESS = 'SUBMIT_IMAGE_SUCCESS';
const SUBMIT_IMAGE_ERROR = 'SUBMIT_IMAGE_ERROR';

export { SUBMIT_IMAGE_BEGIN, SUBMIT_IMAGE_ERROR, SUBMIT_IMAGE_SUCCESS };
